# image
FROM python:3.9-slim
LABEL maintainer="erwingforerocastro@gmail.com"

ENV TYPE_USE "CLI"

# dir
WORKDIR /mvfy

# Paste all project
COPY . .

# sripts
RUN pip install --upgrade pip && \
    pip --no-cache-dir install -r requirements.txt

# execute project
CMD ["python", "mvfy/main.py"]
